# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true
  smart_quotes:  sbquo,rsquo,bdquo,rdquo
highlighter:      rouge

# Permalinks
permalink:        :year/:month/:day/:title/

# Setup
title:            "Patrick de Kok"
tagline:          "On robotics, augmented reality and localization."
description:      "Patrick de Kok enjoys rowing, knows some geometric algebra, and tinkers with robots.  On top of that, he is currently busy with his thesis for the Master of Artificial Intelligence at the <a href=\"http://isla.science.uva.nl/\">Universiteit van Amsterdam</a>."
url:              

author:
  name:           "Patrick de Kok"
  phone:          +31653285375
  email:          dhrdekok@gmail.com
  twitter:        pdkok
  github:         pkok
  linkedin:       pdkok
  pgp_fingerprint: 916AF090DE430ADB
  #pgp_keyserver:  pgp.surfnet.nl

plugins:
  - jekyll-paginate

paginate:         20
