# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     ["tables", "no_intra_emphasis", "autolink", "strikethrough", "space_after_headers", "superscript"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "Patrick de Kok"
tagline:          "On robotics, augmented reality and localization."
description:      "Patrick de Kok is a <a href=\"http://dutchnaoteam.nl\">RoboCup participant</a>, knows some geometric algebra, plays sledge hockey and rows.  On top of that, he is currently occupied with doing his Master's thesis at the <a href=\"http://isla.science.uva.nl/\">Universiteit van Amsterdam</a>, <a href=\"http://www.dbl.tudelft.nl\">Delft University of Technology</a> and <a href=\"http://cybermindnl.com\">Cybermind</a>."
url:              

author:
  name:           "Patrick de Kok"
  url:            
  phone:          +31653285375
  email:          dhrdekok@gmail.com
  facebook:       patrick.dekok
  twitter:        pdkok
  github:         pkok
  linkedin:       pdkok
  disqus:         pdkok
  google_plus:    https://plus.google.com/u/0/+PatrickdeKok

paginate:         20
